#!/usr/bin/env bash
# Shared helpers for ngrok dev scripts (Mac/Linux)

set -euo pipefail

# scripts/lib/ → dev/ngrok (two levels up)
NGROK_DEV_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
NGROK_ENV_FILE="${NGROK_DEV_DIR}/.env"
NGROK_CONFIG="${NGROK_DEV_DIR}/ngrok.yml"
NGROK_URLS_FILE="${NGROK_DEV_DIR}/.ngrok-urls.env"
NGROK_AGENT_API="${NGROK_WEB_ADDR:-127.0.0.1:4040}"

load_env() {
  if [[ ! -f "$NGROK_ENV_FILE" ]]; then
    echo "ERROR: Missing ${NGROK_ENV_FILE}" >&2
    echo "       Run: cp ${NGROK_DEV_DIR}/.env.example ${NGROK_ENV_FILE}" >&2
    exit 1
  fi
  # shellcheck disable=SC1090
  set -a
  source "$NGROK_ENV_FILE"
  set +a

  if [[ -z "${NGROK_AUTHTOKEN:-}" ]]; then
    echo "ERROR: NGROK_AUTHTOKEN is not set in .env" >&2
    exit 1
  fi
  if [[ -z "${NGROK_BASIC_AUTH_USER:-}" || -z "${NGROK_BASIC_AUTH_PASS:-}" ]]; then
    echo "ERROR: NGROK_BASIC_AUTH_USER and NGROK_BASIC_AUTH_PASS must be set in .env" >&2
    exit 1
  fi
}

require_ngrok() {
  if ! command -v ngrok >/dev/null 2>&1; then
    echo "ERROR: ngrok CLI not found. Install: https://ngrok.com/download" >&2
    exit 1
  fi
}

require_curl() {
  if ! command -v curl >/dev/null 2>&1; then
    echo "ERROR: curl is required for health checks" >&2
    exit 1
  fi
}

require_jq() {
  if ! command -v jq >/dev/null 2>&1; then
    echo "ERROR: jq is required. Install: brew install jq" >&2
    exit 1
  fi
}

wait_for_agent() {
  local max_attempts="${1:-30}"
  local i=0
  while (( i < max_attempts )); do
    if curl -sf "http://${NGROK_AGENT_API}/api/tunnels" >/dev/null 2>&1; then
      return 0
    fi
    sleep 1
    ((i++)) || true
  done
  echo "ERROR: ngrok agent did not become ready at http://${NGROK_AGENT_API}" >&2
  return 1
}

write_tunnel_urls() {
  require_curl
  require_jq
  wait_for_agent 45

  local json frontend backend
  json="$(curl -sf "http://${NGROK_AGENT_API}/api/tunnels")"

  frontend="$(echo "$json" | jq -r '.tunnels[] | select(.name=="frontend") | .public_url' | head -1)"
  backend="$(echo "$json" | jq -r '.tunnels[] | select(.name=="backend") | .public_url' | head -1)"

  if [[ -z "$frontend" || "$frontend" == "null" ]]; then
    echo "ERROR: frontend tunnel URL not found" >&2
    echo "$json" | jq '.tunnels[] | {name, public_url, proto}' >&2 || true
    return 1
  fi
  if [[ -z "$backend" || "$backend" == "null" ]]; then
    echo "ERROR: backend tunnel URL not found" >&2
    return 1
  fi

  cat > "$NGROK_URLS_FILE" <<EOF
# Auto-generated by ngrok scripts — do not commit
NGROK_FRONTEND_URL=${frontend}
NGROK_BACKEND_URL=${backend}
NGROK_BACKEND_API_URL=${backend}/api
APP_CORS_EXTRA_ORIGIN_PATTERNS=${frontend}
EOF

  echo ""
  echo "=============================================="
  echo " ngrok tunnels ready"
  echo "=============================================="
  echo " Frontend: ${frontend}"
  echo " Backend:  ${backend}"
  echo " Basic auth user: ${NGROK_BASIC_AUTH_USER}"
  echo ""
  echo " URLs saved to: ${NGROK_URLS_FILE}"
  echo ""
  echo " Next steps:"
  echo "  1. Spring Boot:  SPRING_PROFILES_ACTIVE=ngrok mvn spring-boot:run"
  echo "     (or export vars from .ngrok-urls.env)"
  echo "  2. Angular:      see dev/ngrok/angular/environment.ngrok.ts.example"
  echo "  3. Health check: ./scripts/health-check.sh"
  echo "=============================================="
}
